apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-depl
  labels:
    app: my-app
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: hieubui1307/test:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080